var mapa =
{
	"relaciones": [{
		"intervencion_s": 0,
		"intervencion_f": 0,
		"intervencion_nrg": 0,
		"intervencion_e": 0,
		"intervencion_fr": 0,
		"intervencion_d": 0
	}, {
		"intervencion_s": 1,
		"intervencion_f": 1,
		"intervencion_nrg": 1,
		"intervencion_e": 1,
		"intervencion_fr": 1,
		"intervencion_i": 1,
		"intervencion_d": 1
	}, {
		"intervencion_s": 2,
		"intervencion_f": 2,
		"intervencion_nrg": 2,
		"intervencion_e": 2,
		"intervencion_fr": 2,
		"intervencion_i": 2,
		"intervencion_d": 2
	}, {
		"intervencion_s": 3,
		"intervencion_f": 3,
		"intervencion_nrg": 3,
		"intervencion_e": 3,
		"intervencion_fr": 3,
		"intervencion_i": 3,
		"intervencion_d": 3
	}, {
		"intervencion_s": 4,
		"intervencion_f": 4,
		"intervencion_nrg": 4,
		"intervencion_e": 4,
		"intervencion_fr": 4,
		"intervencion_i": 4,
		"intervencion_d": 4
	}, {
		"intervencion_s": 5,
		"intervencion_f": 5,
		"intervencion_nrg": 5,
		"intervencion_e": 5,
		"intervencion_fr": 5,
		"intervencion_i": 5,
		"intervencion_d": 5
		
		}, {
		"intervencion_s": 6,
		"intervencion_f": 6,
		"intervencion_nrg": 6,
		"intervencion_e": 6,
		"intervencion_fr": 6,
		"intervencion_i": 6,
		"intervencion_d": 6
		}, {
		"intervencion_s": 7,
		"intervencion_f": 7,
		"intervencion_nrg": 7,
		"intervencion_e": 7,
		"intervencion_fr": 7,
		"intervencion_i": 7,
		"intervencion_d": 7
		}, {
		"intervencion_s": 8,
		"intervencion_f": 8,
		"intervencion_nrg": 8,
		"intervencion_e": 8,
		"intervencion_fr": 8,
		"intervencion_i": 8,
		"intervencion_d": 8
		}, {
		"intervencion_s": 9,
		"intervencion_f": 9,
		"intervencion_nrg": 9,
		"intervencion_e": 9,
		"intervencion_fr": 9,
		"intervencion_i": 9,
		"intervencion_d": 9
		}, {
		"intervencion_s": 10,
		"intervencion_f": 10,
		"intervencion_nrg": 10,
		"intervencion_e": 10,
		"intervencion_fr": 10,
		"intervencion_i": 10,
		"intervencion_d": 10
		}, {
		"intervencion_s": 11,
		"intervencion_f": 11,
		"intervencion_nrg": 11,
		"intervencion_e": 11,
		"intervencion_fr": 11,
		"intervencion_i": 11,
		"intervencion_d": 11
		}, {
		"intervencion_s": 12,
		"intervencion_f": 12,
		"intervencion_nrg": 12,
		"intervencion_e": 12,
		"intervencion_fr": 12,
		"intervencion_i": 12,
		"intervencion_d": 12
		}, {
		"intervencion_s": 13,
		"intervencion_f": 13,
		"intervencion_nrg": 13,
		"intervencion_e": 13,
		"intervencion_fr": 13,
		"intervencion_i": 13,
		"intervencion_d": 13
		}, {
		"intervencion_s": 14,
		"intervencion_f": 14,
		"intervencion_nrg": 14,
		"intervencion_e": 14,
		"intervencion_fr": 14,
		"intervencion_i": 14,
		"intervencion_d": 14
		}, {
		"intervencion_s": 15,
		"intervencion_f": 15,
		"intervencion_nrg": 15,
		"intervencion_e": 15,
		"intervencion_fr": 15,
		"intervencion_i": 15,
		"intervencion_d": 15
		}, {
		"intervencion_f": 16,
		"intervencion_nrg": 16,
		"intervencion_e": 16,
		"intervencion_fr": 16,
		"intervencion_i": 16,
		"intervencion_d": 16
		}, {
		"intervencion_f": 17,
		"intervencion_nrg": 17,
		"intervencion_i": 17,
		"intervencion_d": 17
		}, {
		"intervencion_f": 18,
		"intervencion_nrg": 18,
		"intervencion_i": 18,
		"intervencion_d": 18
		}, {
		"intervencion_f": 19,
		"intervencion_nrg": 19,
		"intervencion_i": 19,
		"intervencion_d": 19
		}, {
		"intervencion_f": 20,
		"intervencion_nrg": 20,
		"intervencion_i": 20,
		"intervencion_d": 20
		}, {
		"intervencion_f": 21,
		"intervencion_nrg": 21,
		"intervencion_i": 21,
		"intervencion_d": 21
		}, {
		"intervencion_f": 22,
		"intervencion_nrg": 22,
		"intervencion_i": 22,
		"intervencion_d": 22
		}, {
		"intervencion_f": 23,
		"intervencion_nrg": 23,
		"intervencion_i": 23,
		"intervencion_d": 23
		}, {
		"intervencion_s": 16,
		"intervencion_f": 24,
		"intervencion_nrg": 24,
		"intervencion_e": 16,
		"intervencion_fr": 16,
		"intervencion_i": 24,
		"intervencion_d": 24
		}, {
		"intervencion_s": 17,
		"intervencion_f": 25,
		"intervencion_nrg": 25,
		"intervencion_e": 17,
		"intervencion_fr": 17,
		"intervencion_i": 25,
		"intervencion_d": 25
		}, {
		"intervencion_s": 18,
		"intervencion_f": 26,
		"intervencion_nrg": 26,
		"intervencion_e": 18,
		"intervencion_fr": 18,
		"intervencion_i": 26,
		"intervencion_d": 26
		
		
	}]
};
